"""add some columns

Revision ID: 900966ae3b5b
Revises: ce542c5a6465
Create Date: 2021-10-27 10:33:25.771311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900966ae3b5b'
down_revision = 'ce542c5a6465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('name', sa.String(length=25), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=25), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('groups', 'name')
    # ### end Alembic commands ###
