"""add some columns

Revision ID: 941cc33e5621
Revises: 57888530b421
Create Date: 2021-10-26 08:13:26.523015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941cc33e5621'
down_revision = '57888530b421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(), nullable=False))
    op.add_column('groups', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('biography', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'biography')
    op.drop_column('groups', 'name')
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
