"""delete createdAt and updatedAt columns

Revision ID: c8ffa1655f43
Revises: 900966ae3b5b
Create Date: 2021-10-28 11:31:55.377512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8ffa1655f43'
down_revision = '900966ae3b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'updatedAt')
    op.drop_column('comments', 'createdAt')
    op.drop_column('groups', 'updatedAt')
    op.drop_column('groups', 'createdAt')
    op.drop_column('likes', 'updatedAt')
    op.drop_column('likes', 'createdAt')
    op.drop_column('messages', 'updatedAt')
    op.drop_column('messages', 'createdAt')
    op.drop_column('moments', 'updatedAt')
    op.drop_column('moments', 'createdAt')
    op.drop_column('users', 'updatedAt')
    op.drop_column('users', 'createdAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('moments', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('moments', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('likes', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('likes', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
