"""drop some columns

Revision ID: 57888530b421
Revises: 75a4fef338d3
Create Date: 2021-10-26 08:07:02.585884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57888530b421'
down_revision = '75a4fef338d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment')
    op.drop_column('groups', 'name')
    op.drop_column('users', 'biography')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('biography', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
